### ISSUE TITLE
Specify SHA2 as the hash function rather than SHAKE

### ISSUE THREAD

**Issue by danvangeest** [lamps-wg/cms-ml-dsa#1]
https://mailarchive.ietf.org/arch/msg/spasm/aWaBnRcrYGlDHTxqj9u72QEPm-E/

If we keep actual digestAlgorithms (not id-digest-none) for non-SignedAttributes, add similar text as RFC 8419 to make it explicit that a prehash isn't generated. And in this case we set the digestAlgorithm as whatever digest is used internally to ML-DSA.

```
When signing with Ed448, the
digestAlgorithm MUST be id-shake256, and the algorithm parameters
field MUST be absent.

  NOTE: Either id-sha512 or id-shake256 is used as part to the
  private key signing operation.  However, the private key signing
  operation does not take a message digest computed with one of
  these algorithms as an input.
```

**Comment by danvangeest** [comment]
Something like id-digest-none (id-hashIdentity) was proposed for draft-ietf-curdle-cms-eddsa-signatures (RFC 8419).  There wasn't much discussion, the decision was to avoid the extra identifier: https://mailarchive.ietf.org/arch/msg/curdle/HG4ED83kc2mf9n4j-O_zL3PGGKg/

**Comment by adam-r-ncsc** [comment]
For ML-DSA-44 we've also got a choice of whether to specify SHA-512 or SHA-256. [FIPS 204](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.204.pdf) describes SHA256 and SHA512 as examples of valid pre-hash algorithms (as well as SHAKE128), but the [NIST OID assignments for pre-hash ML-DSA](https://csrc.nist.gov/projects/computer-security-objects-register/algorithm-registration) only include SHA512, which would imply a preference on NIST's part for SHA512 as a pre-hash algorithm for all ML-DSA variants.

**Comment by danvangeest** [comment]
My question to the list, linked in the issue description, asked if we should just use SHA512.  The only response to this was from Deirde in favour of that: https://mailarchive.ietf.org/arch/msg/spasm/tFMKlZMjDI9npKugf6_Mg23_01o/
So let's do that.
