### ISSUE TITLE
SHA-512 reference

### ISSUE THREAD

**Issue by adam-r-ncsc** [lamps-wg/cms-ml-dsa#8]
RFC 8017 is used as a reference for SHA-512 as a message digest algorithm - I'd have expected RFC 5754.

**Comment by danvangeest** [comment]
This is a good point.  This came from text copied from the cms-sphincs-plus draft.  I can update our draft.  Would you like to bring this up on the list and/or direct to Russ for cms-sphincs-plus?  If not, I can.

**Comment by danvangeest** [comment]
On the other hand, RFC 8017 is the update of RFC 3447 which brought id-sha512 into the IETF, so maybe RFC 8017 is appropriate.  RFC 5754 brought it into CMS though.

**Comment by adam-r-ncsc** [comment]
Seems a bit trivial for the list so long as cms-sphincs-plus and this draft are aligned - I'll email Russ directly.

**Comment by danvangeest** [comment]
Fixed with a commit fa06e8
